spring:
  application:
    name: hostel-management-system
  data:
    mongodb:
      uri: mongodb://localhost:27017/hostel_management
      auto-index-creation: true
  security:
    user:
      name: admin
      password: admin123

server:
  port: 8080

app:
  jwt:
    secret: hostel_management_secret_key_2024_spring_boot_version
    expiration: 86400000 # 24 hours in milliseconds

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: false
  writer-with-default-pretty-printer: true

logging:
  level:
    com.hostel: DEBUG
    org.springframework.security: DEBUG 