apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-data-pvc
  namespace: hostel-management
  labels:
    app.kubernetes.io/name: hostel-management-system
    app.kubernetes.io/component: backend
    app.kubernetes.io/version: "1.0.0"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  # storageClassName will be set by cloud-specific overlays
  # storageClassName: standard  # GKE
  # storageClassName: gp3       # AWS EKS
  # storageClassName: managed-premium  # Azure AKS 