apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: hostel-management
  labels:
    app.kubernetes.io/name: hostel-management-system
    app.kubernetes.io/component: backend
    app.kubernetes.io/version: "1.0.0"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
    prometheus.io/path: "/api/metrics"
spec:
  selector:
    app.kubernetes.io/name: hostel-management-system
    app.kubernetes.io/component: backend
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP
  type: ClusterIP
  sessionAffinity: None 