apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: hostel-management
  labels:
    app.kubernetes.io/name: hostel-management-system
    app.kubernetes.io/component: frontend
    app.kubernetes.io/version: "1.0.0"
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
spec:
  selector:
    app.kubernetes.io/name: hostel-management-system
    app.kubernetes.io/component: frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
  sessionAffinity: None 