apiVersion: v1
kind: Service
metadata:
  name: springboot-mysql-service
  namespace: hostel-management
  labels:
    app.kubernetes.io/name: hostel-management-system
    app.kubernetes.io/component: springboot-mysql
    app.kubernetes.io/version: "1.0.0"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
    prometheus.io/path: "/actuator/prometheus"
spec:
  selector:
    app.kubernetes.io/name: hostel-management-system
    app.kubernetes.io/component: springboot-mysql
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: management
    port: 8081
    targetPort: 8081
    protocol: TCP
  type: ClusterIP
  sessionAffinity: None 