# Development-specific configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  template:
    spec:
      containers:
      - name: backend
        env:
        - name: NODE_ENV
          value: "development"
        - name: LOG_LEVEL
          value: "debug"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-mongodb
spec:
  template:
    spec:
      containers:
      - name: springboot-mongodb
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "development"
        - name: LOGGING_LEVEL_COM_HOSTEL
          value: "DEBUG"
        - name: SPRING_JPA_SHOW_SQL
          value: "true"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-mysql
spec:
  template:
    spec:
      containers:
      - name: springboot-mysql
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "development"
        - name: LOGGING_LEVEL_COM_HOSTEL
          value: "DEBUG"
        - name: SPRING_JPA_SHOW_SQL
          value: "true" 